### ISSUE TITLE
[feature request] specify encoder/chipset for de brujin brute forcing with rogue pro

### ISSUE THREAD

**Issue by thesle3p** [ComThings/PandwaRF#100]
Unless I am missing something there is no way to specify the encoder when doing a de brujin brute force. Would it be possible to add the brute force customization options for de brujin attacks that we have for conventional brute forcing?

**Comment by trollwookiee** [comment]
You are totally right. We will add this feature to DeBruijn.

**Comment by trollwookiee** [comment]
Scheduled for Android release 1.7.0

**Comment by dapollo** [comment]
Thanks Sir.

**Comment by trollwookiee** [comment]
Released in Android App 1.7.0
