### ISSUE TITLE
Get error when listen call rxListen

### ISSUE THREAD

**Issue by masoodkhademi** [ComThings/PandwaRF#102]
I added https://github.com/ComThings/PandwaRF/wiki/Android-Developer-SDK
 Android Developer SDK to my app and after that connect yardstick to my phone via usb
when listened to rxListen I get this error:
CC1111_NPI_LIBUSB: USB Read error: 192 bytes, error -8
CC1111_NPI: NPI RX thread: Read error -8

please help

**Comment by trollwookiee** [comment]
YS1 is not officially supported. We may support it at some point, but not in an immediate future.
