### ISSUE TITLE
Parse sever check failed

### ISSUE THREAD

**Issue by rtfclb8** [ComThings/PandwaRF#104]
BLE and RF update are greyed out. Did a manual update using latest .zip file, but still greyed out. I have an older PandwaRF.

Thanks!

**Comment by trollwookiee** [comment]
what model & HW revision ? 
Please indicate what are your latest App & FW versions please

**Comment by rtfclb8** [comment]
I tried it again, and I was able to upgrade.

Thanks,

George

**Comment by trollwookiee** [comment]
Thanks for feedback
