### ISSUE TITLE
Kaiju - you are not logged

### ISSUE THREAD

**Issue by Cloud-Forge** [ComThings/PandwaRF#108]
In the Android App, I connect the Rogue Pro to the APP.

I go to the Kaiju menu. 
(I have previously created a Kaiju account with a gmail address that is the one used on my Android device).

When I press the "LOGIN" button nothing happens.

**Comment by dapollo** [comment]
It's the same problem I had a couple of days ago.
solution?
In the android application.
Go to about.
then sent debug trace with your kaijui account email.
pandwarf rogue administrators should enable it.

**Comment by Cloud-Forge** [comment]
> It's the same problem I had a couple of days ago.
> solution?
> In the android application.
> Go to about.
> then sent debug trace with your kaijui account email.
> pandwarf rogue administrators should enable it.

Thanks Dapollo, will do that.

**Comment by Rem193** [comment]
Hi @Cloud-Forge , your issue is under investigation, which email address do you use to connect to Kaiju ?

**Comment by Rem193** [comment]
Hi,

Due to no more feedback provided, this issue is closed.
If you still have an issue with Kaiju login please open a new issue.

PandwaRF Team.
