### ISSUE TITLE
Kaiju - HTTP 403: Product Already Assigned To Another User

### ISSUE THREAD

**Issue by Opcode-Void** [ComThings/PandwaRF#109]
I had just bought and paired a PandwaRF Rogue Pro to phone today.
First issue that is causing a problem is every time I try to sign into my Kaiju account, it says the Rogue Pro is already in use on another account?

A second issue I have that isn't a problem and more of a curiosity, I can't bond with the PandwaRF and prompts repeatedly to bond.
However after bonding, I can still connect to it from another phone.

**Comment by trollwookiee** [comment]
This issue can happen when we do tests on products during assembly. The tested product ends up being assigned to our Kaiju test account. In most cases, the PandwaRF is unlinked to the Kaiju test account, but sometimes one product slips throught the check. This is fixed immediatly when we are notified.
