### ISSUE TITLE
Update the detail description of parameters for scripting

### ISSUE THREAD

**Issue by Redouan29** [ComThings/PandwaRF#11]
An update on wiki that describe details of parameters for writing scripts for PandwaRF.
See the wiki and the TODO list; https://github.com/ComThings/PandwaRF/wiki/Developer-JavaScript-Functions-Mapping

Thanks!

**Comment by trollwookiee** [comment]
https://github.com/ComThings/PandwaRF/wiki/Developer-JavaScript-Functions-Mapping has been updated.

**Comment by Redouan29** [comment]
Thanks!
