### ISSUE TITLE
received codes logging 

### ISSUE THREAD

**Issue by dav781** [ComThings/PandwaRF#13]
I would like being able to feed audio files to apk to decode and analyse signals received with a sdr. also the next code generation (same or rolling) might use the recorded audio signal as a Base. 
alternatively, I'd like the ability to leave "sniff mode" on and log/analyze all received signals. maybe with direct USB connection that would be feasible? 
last but not least, an integrated archive of known signals/parameters to make our life easier? 
thx

**Comment by trollwookiee** [comment]
Our app cannot process raw files (I/Q) from SDR.
Will keep you updated on USB status.
