### ISSUE TITLE
App version 1.2.42 broke BruteForce

### ISSUE THREAD

**Issue by yaba** [ComThings/PandwaRF#15]
I've updated today two devices to 1.2.42 app version.
Brute force does not work anymore. 1 second after start it stops automatically.

Device 1: Samsung GT-i9300 - Android 7.1.2
Device 2: Samsung Galaxy Tab A - Android 5.1.1

**Comment by trollwookiee** [comment]
fixed on 1.2.43

**Comment by yaba** [comment]
Not really, I'm having the same issues in both of the devices.
Although, it last a little longer, than jumps to the final and stops.
I'll try to post later the logs and some pics to explain better. 
Using Chipset / DIO or PT seems to be worse, starts and stops.

**Comment by trollwookiee** [comment]
I will handle this when i return to the office. Thanks for the feedback. I
really appreciate users feedbacks.
