### ISSUE TITLE
Bluetooth LE services and characteristics documentation

### ISSUE THREAD

**Issue by ptigas** [ComThings/PandwaRF#24]
Hi,

I am interested in developing a mobile application using PandwaRF and would be great if I could use directly Bluetooth LE services and characteristics.

Could you please provide some documentation? Also, are there any plans open sourcing the data processing part or it's proprietary?

p.

**Comment by trollwookiee** [comment]
Documention effort for BLE services and characterisitics is ongoing. ETA december 2017.

**Comment by kevanlanister735** [comment]
Still ongoing??? If this was documented, we would also be able to use BLE Services from Web Bluetooth?

**Comment by trollwookiee** [comment]
First draft of BLE services documentation have been added to wiki here: [PandwaRF BLE Services & characteristics](https://github.com/ComThings/PandwaRF/wiki/Developer-BLE-Services-Characteristics).

This is OK to start with. What remains to be described is

- RfCat messages description
- Mapping of RfCat messages onto BLE NUS
- RfCat message segmentation process
