### ISSUE TITLE
PandwaRF stops rx/tx from android app

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#28]
PandwaRF stops receiving/transmitting frequently (every 5 - 20 time random). Registers also can not be read when this happens. I need to reconnect (disconnect/connect). Sometimes disconnect and turning BT off does not help - blue light always on, so I need to press reset on the unit.
No errors in BLE log.

**Comment by TadasSu** [comment]
p.s. spectrum analyzer also does not work when this happens. I only can read device info in Bus service tab.
Firmware 0.9.19 / 1.0.17

**Comment by ryan-dsouza** [comment]
Sounds like a similar issue to #26

**Comment by TadasSu** [comment]
It always works for the fist time when connected, but yes, it sounds *almost* similar like #26 issue.

**Comment by Sikloz** [comment]
Same issue as above RX/TX sniffing/transmitting not working nor is the spec analyser but SA works on initial startup of the app.

**Comment by trollwookiee** [comment]
Fixed in V1.2.58
