### ISSUE TITLE
2-FSK doesnt work in Android SDK and Example app

### ISSUE THREAD

**Issue by ryan-dsouza** [ComThings/PandwaRF#32]
Tried the following with the Android SDK gollumDongle.txSetup(433913879, 00, 3200);  2-FSK transmission, with no success.

Exact same thing with ASK works  gollumDongle.txSetup(433913879, 48, 3200); // 0x30 

Tried the changing it on the example SDK app from ASK to 2-FSK. No success.  The PandwaRF app works fine with 2-FSK. (Atleast it transmits and Receives at a default deviation)

Was expecting the SDK /Example app to transmit at some default deviation, which doesn't seem to happen. Any help appreciated.

**Comment by trollwookiee** [comment]
Fixed in Gollum Lib 0.8.0/app 1.3.0
