### ISSUE TITLE
USB Crashes for Payload more than 250 Bytes < 500bytes

### ISSUE THREAD

**Issue by ryan-dsouza** [ComThings/PandwaRF#36]
Works well for Payloads below the page limit. Works first time for say 400 bytes. 
After that the USB driver crashes. 
400 bytes works over Bluetooth

Versions 
Android SDK 0.7.22
Nordic 0.9.19
C1111 1.0.17

Logs
CC1111_RF: rfsub1g_cc1111_Rf_Setup_Config
11-25 15:30:36.075 24665-32185/xx.co.xx V/  CC1111_RF: rfsub1g_cc1111_Rf_ConfigBuffer_Erase
11-25 15:30:36.075 24665-32185/xx.co.xx V/  CC1111_RF: rfsub1g_cc1111_Rf_GetBulkConfig
11-25 15:30:36.075 24665-32185/xx.co.xx D/   CC1111_RF_CONTROL: cc1111_peek (0xdf00 62)
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: Enter npi_SendSynchDataRfcat
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: Enter npi_sendframeRfcat
11-25 15:30:36.075 24665-32185/xx.co.xx D/     CC1111_NPI_LIBUSB: npi_libusb_send(0xff 0x80 4)
11-25 15:30:36.075 24665-32185/xx.co.xx E/     CC1111_NPI_LIBUSB: Write Error
11-25 15:30:36.075 24665-32185/xx.co.xx E/    CC1111_NPI: Rfcat frame not sent, app: ff, cmd: 80, len: 4
11-25 15:30:36.075 24665-32185/xx.co.xx E/  CC1111_RF: rfsub1g_cc1111_Rf_GetBulkConfig: Failed, readburst returned null
11-25 15:30:36.075 24665-32185/xx.co.xx E/  CC1111_RF: rfsub1g_cc1111_Rf_Setup_Config: Failed to setup config
11-25 15:30:36.075 24665-32185/xx.co.xx V/  CC1111_RF_MSG: rfsub1g_cc1111_Rf_SetMdmModulation Called with PARAMETERS: modulation: 0, invert: -1
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: npi_SendAsynchDataRfcat: Posting Asynch data
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: Enter npi_sendframeRfcat
11-25 15:30:36.075 24665-32185/xx.co.xx D/     CC1111_NPI_LIBUSB: npi_libusb_send(0xbf 0x54 2)
11-25 15:30:36.075 24665-32185/xx.co.xx E/     CC1111_NPI_LIBUSB: Write Error
11-25 15:30:36.075 24665-32185/xx.co.xx E/  CC1111_RF_MSG: rfsub1g_cc1111_Rf_SetMdmModulation: Failed, reason: set Power failed 
11-25 15:30:36.075 24665-32185/xx.co.xx V/  CC1111_RF_MSG: rfsub1g_cc1111_Rf_SetFreq Called with PARAMETER: freq: 433913879
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: npi_SendAsynchDataRfcat: Posting Asynch data
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: Enter npi_sendframeRfcat
11-25 15:30:36.075 24665-32185/xx.co.xx D/     CC1111_NPI_LIBUSB: npi_libusb_send(0xbf 0x52 4)
11-25 15:30:36.075 24665-32185/xx.co.xx E/     CC1111_NPI_LIBUSB: Write Error
11-25 15:30:36.075 24665-32185/xx.co.xx E/  CC1111_RF_MSG: rfsub1g_cc1111_Rf_SetFreq: Failed, reason: set Freq failed 
11-25 15:30:36.075 24665-32185/xx.co.xx V/  CC1111_RF_MSG: rfsub1g_cc1111_Rf_SetMdmDRate Called with PARAMETER: Data Rate: 3200
11-25 15:30:36.075 24665-32185/xx.co.xx V/    CC1111_NPI: npi_SendAsynchDataRfcat: Posting Asynch d

**Comment by trollwookiee** [comment]
Fixed.
