### ISSUE TITLE
Pandwarf not working on Galaxy S7 + android 6.0.1 ($ rm -Rf /*)

### ISSUE THREAD

**Issue by trollwookiee** [ComThings/PandwaRF#4]
Hey I don't seem to be able to make Pandwarf work on my phone: Galaxy S7 + android 6.0.1 // for example the spectrum analyser doesn't show graph and when it does, the sampling seems to stop after one second and the entire app gets irresponsive. Then i'm forced to quit and reinit the app. I tried to wipe cache, and reset config, but still no luck. - Advice? -

Galaxy S7 + android 6.0.1

**Comment by PsychoBitchy** [comment]
Some more details:
I'm able to make the SpecAn to work by flushing app data + cache.
However it displays a very slow data rate.
If I stop it / reset it / or change RF band scale, the data rate drops to 0 Meas/s and the app displays no measurements until I flush cache / app data.

![screenshot_20170117-183447](https://cloud.githubusercontent.com/assets/17138173/22033829/658211fc-dcea-11e6-9eba-e0923dae5b40.png)

![screenshot_20170117-183459](https://cloud.githubusercontent.com/assets/17138173/22033843/71fd8a9c-dcea-11e6-9311-bea5e03aaa31.png)

![screenshot_20170117-183646](https://cloud.githubusercontent.com/assets/17138173/22033849/772274ce-dcea-11e6-82e8-e630834dd080.png)

![screenshot_20170117-183552](https://cloud.githubusercontent.com/assets/17138173/22033855/7f8ff6e0-dcea-11e6-91e0-b2802a13f7ab.png)

![screenshot_20170117-184942](https://cloud.githubusercontent.com/assets/17138173/22033877/99de8b56-dcea-11e6-8c64-5d8cb7aa1718.png)

![screenshot_20170117-184255](https://cloud.githubusercontent.com/assets/17138173/22033896/a7e8c342-dcea-11e6-85d4-f7c800393346.png)

**Comment by PsychoBitchy** [comment]
I also stumbled upon an erratic behaviour on the SpecAn screen: sometime just swiping over the graph results in the frequency graph being originated at 0 mhz:
![screenshot_20170117-184153](https://cloud.githubusercontent.com/assets/17138173/22034337/4507e99a-dcec-11e6-84e6-45ba5286aad7.png)

**Comment by trollwookiee** [comment]
Thanks.  
If you stick to a static setting when doing a Specan, does it work ? 
Please also check https://github.com/ComThings/PandwaRF/wiki/Support-Known-Issues#spectrum-analyzer-doesnt-support-slidingzoomingpinching

We have to rework the specan UI. This is scheduled for march.

Besides of Specan, what are the other errors you have ? Disconnect ? RX errors ?

**Comment by PsychoBitchy** [comment]
If by " static setting " you're meaning " flush cache, reboot then don't touch anything on default setting, yes, well sort of: I hadn't been able to locate any keyfob TX with this, but it displays a graph.  
Moreover it feels like the app is almost sucking all my device CPU, as the home button becomes laggy.

**Comment by duan78** [comment]
Same problem here (SGS 7 Edge)
--> SpecAn freeze (or blank after stop/reload)

**Comment by trollwookiee** [comment]
High CPU usage has been fixed in 1.236. Please check.

**Comment by PsychoBitchy** [comment]
Well, sorry to bring bad news. 
In the meantime s7 went on Android 7.  
This time, with last firmware, SpecAn doesn't show at all.
![screenshot_20170421-234438](https://cloud.githubusercontent.com/assets/17138173/25330231/3993bea6-28df-11e7-9306-ea548e75653f.png)
![screenshot_20170421-234409](https://cloud.githubusercontent.com/assets/17138173/25330232/3c879b6e-28df-11e7-8a0b-b6af9c82f948.png)
![screenshot_20170421-234417](https://cloud.githubusercontent.com/assets/17138173/25330234/3f34a64a-28df-11e7-9abf-63f643df1868.png)

**Comment by PsychoBitchy** [comment]
Hello.  
I have been able to finally get it to work and it's a marvel! 
The specAn however sometimes stops working and I have to kill the background paused thread to get it again.  
There's still a somewhat unreliable worker around there but nothing rendering the app unusable.

You can close that thread. 
Thank you for your dedication.

**Comment by trollwookiee** [comment]
Great !

**Comment by alastacat** [comment]
I seem to be having the exact same problem using my pixel 2 using android 8.0.0.  Software version 0.9.17 and Firmware version 1.0.17.
Flushing app data + cache makes the spectrum analyser run, but the data rate drops to 0 Meas/s and not picking up signal. 
Next time I run the spec analyser it doesn't start until flush again.  
Is there any detail on how this was fixed?

**Comment by trollwookiee** [comment]
On some phones, Specan causes issues. 
In general, SpecAn has problems to restart. This is cause by some background tasks not properly cleaned.
I am investigating.

**Comment by trollwookiee** [comment]
If issue persists, please open a new defect.
