### ISSUE TITLE
Detect carrier frequency problems

### ISSUE THREAD

**Issue by ellenhill94** [ComThings/PandwaRF#46]
I am trying to use the PandwaRF to detect the base frequency of signals in the range 433.5 MHz to 434.5 MHz. I have used the API for Android, and have used rfSpecanGetRssi to get RSSI values in this range over a period of 5 seconds (refresh rate 30ms). Then I calculate the frequency based on the RSSI values retrieved. 
However, this method is not working well as the RSSI values are not very accurate, especially if I use an antenna. Has anybody had success with any other methods for obtaining the base frequency, or have any ideas for a better method?
Thanks in advance!

**Comment by trollwookiee** [comment]
Do you think an API to get the frequency with the highest RSSI directly from the HW would be better ?

**Comment by ellenhill94** [comment]
Yes definitely worth a try!
