### ISSUE TITLE
Link to button

### ISSUE THREAD

**Issue by sjames02** [ComThings/PandwaRF#49]
Hi,

I own a Rogue Pro, unless I am misunderstanding the 'link to button' feature, I don't believe it is working for me.

After capturing the data from an OOK transmitter and then confirming successful capture by re-transmitting it, I then try to link the configuration/data to a physical button. Upon pressing the hardware button (short press) i do get a red LED, however it does not appear to be transmitting anything. I have tried pressing the button from within 'Bus Service Extended' of which also presents a red LED with no apparent transmission?

Appreciated.

**Comment by trollwookiee** [comment]
Hi,

What HW revision do you have ?

**Comment by sjames02** [comment]
Its E4, Rogue Pro. I purchased just a couple of weeks ago. Firmware is up to date, 1.0.22.

**Comment by trollwookiee** [comment]
fix is ongoing.

**Comment by trollwookiee** [comment]
Fixed in 1.4.8
