### ISSUE TITLE
Gollum 0.9.8 migrate problems

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#50]
Lats release Gollum 0.9.8 not have dependency to nrftoolbox. So after update from 0.9.3 I have build errors. 

P.S. To fix need manually add ```implementation 'com.comthings.pandwarf:nrftoolbox:1.0.9'```

Next problem -  java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
   at com.comthings.gollum.api.gollumandroidlib.utils.Utils.log

P.S. To fix this need add ```Fabric.with(this, new Crashlytics());```

**Comment by trollwookiee** [comment]
Can you please check with https://github.com/ComThings/PandwaRF/commit/82b41307cfe695945d6165ca84fd6d2238b3d024 and 'com.comthings.pandwarf:gollum:0.9.9' ? 
Thanks
