### ISSUE TITLE
Gollum 0.9.10 not work on arm64

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#54]
Last sdk 0.9.10 not work on arm64
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.app.test/app_lib/libusb1.0.so" is 32-bit instead of 64-bit`

Test device - Xiaomi Redmi Note 3

**Comment by trollwookiee** [comment]
Migration to 64-bit done.
Fixed in Gollum Android Lib 0.9.27
Cf. https://comthings.github.io/PandwaRF/ and 
https://mymavenrepo.com/repo/l8uzsKQuWwYGByPmlbZ4/com/comthings/pandwarf/gollum/0.9.27/
