### ISSUE TITLE
updateFirmwareCC1111 using hex file not work

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#55]
Update firmware using [updateFirmwareCC1111](https://comthings.github.io/PandwaRF/v0.9.10/com/comthings/gollum/api/gollumandroidlib/GollumDongle.html#updateFirmwareCC1111-java.lang.String-com.comthings.gollum.api.gollumandroidlib.callback.GollumCallbackGetInteger-) not work.

After call updateFirmwareCC1111 it immediately call callback (GollumCallbackGetInteger ) with 0 and no any exception. And not update CC1111.

**Comment by trollwookiee** [comment]
Fixed in 0.9.10

**Comment by LSDsl** [comment]
Tested on 0.9.10 - not work.

**Comment by trollwookiee** [comment]
Sorry typo, 0.9.10 is current version. Next one is 0.9.11. Updated Milestone.

**Comment by trollwookiee** [comment]
can you check the lib 0.9.11 ? https://comthings.github.io/PandwaRF/

**Comment by LSDsl** [comment]
Also I have question about cbOnProgress listener. In my test it called with parameters (pages) from 2 to 28. Why it starts from 2 and ends with 28 ?? Max will be 28 always? After 28 was cbOnFinish with exception as I described above.

**Comment by trollwookiee** [comment]
1) What is the error type you get in cbOnFinish() ?
2) cbOnProgress listener: 2 to 28 is normal. I will describe more in wiki.

**Comment by LSDsl** [comment]
There is no any error type - only exception "Gollum firmware update failed"  (look above) https://comthings.github.io/PandwaRF/v0.9.11/com/comthings/gollum/api/gollumandroidlib/callback/GollumCallback.html

**Comment by trollwookiee** [comment]
Ok, this spurious call to cbOnFinish() is fixed now. Thanks for report.

**Comment by LSDsl** [comment]
> Pages generally range from 1 to N=30, but this may vary according to FW size.
I need to know current page and max page count. But how I can know max N for updating FW?

I need this to show progress like in PandwaRF app.
![image1](https://user-images.githubusercontent.com/1483011/42947255-a1062480-8b75-11e8-9130-a4b12838cfdc.jpeg)

**Comment by trollwookiee** [comment]
https://comthings.github.io/PandwaRF/v0.9.12/index.html
When called, the hex file is analyzed and callback cbOnPageTotalUpdate is called with total number of pages to be flashed (N).
N is max page count.
cbOnProgress contains current page.

**Comment by LSDsl** [comment]
But now onSoftwareVersionReceived onFirmwareVersionReceived work incorrect - bug https://github.com/ComThings/PandwaRF/issues/60

**Comment by LSDsl** [comment]
Also connection time increased in last sdk and in log many errors like

> W/System: Ignoring header X-Parse-Client-Key because its value was null.
>           Ignoring header X-Parse-Application-Id because its value was null.
