### ISSUE TITLE
Make PandwaRF compatibile with Universal Radio Hacker

### ISSUE THREAD

**Issue by evazzoler** [ComThings/PandwaRF#56]
Referring to the useful article on your DOCU section (https://github.com/ComThings/PandwaRF/wiki/Android-Brute-Force-Tutorial), would be wonderful if the first step could be made with PandwaRF (instead RTL-SDR) in order to have ONE unique tool in the hands.

**Comment by trollwookiee** [comment]
Exporting data from URH to PandwaRF for Brute force will soon be possible.

**Comment by trollwookiee** [comment]
Released in 1.4.13.
Please refer to https://github.com/ComThings/PandwaRF/wiki/Android-Brute-Force-Session-Import-Tutorial#using-urh---universal-radio-hacker-xml
