### ISSUE TITLE
RX power amplifier option does not work

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#62]
RSSI in specan is the same with different RF Power Amplifiers options.
I tried these: Turn off TX/RX amp / Turn on RX amp always / Turn on RX apm only when receiving / Turn on RX/TX auto

![screenshot_20181004-222405](https://user-images.githubusercontent.com/6928835/46497921-9771de00-c824-11e8-900f-4e50c168c4bc.jpg)
![screenshot_20181004-222431](https://user-images.githubusercontent.com/6928835/46497923-9771de00-c824-11e8-82a1-de579bfec1cc.jpg)
![screenshot_20181004-222449](https://user-images.githubusercontent.com/6928835/46497924-9771de00-c824-11e8-8cc9-97008d5bc144.jpg)

**Comment by trollwookiee** [comment]
I made some tests on App v1.4.20/Nordic v0.11.1/CC1111 v1.1.1.
I measure a difference of 9 dB when RF power amplifiers are ON in RX. 

- With RX amplifiers OFF: RSSI = **-30dBm** at 433.4MHz
![screenshot_20181115-171909](https://user-images.githubusercontent.com/4953605/48566077-3b59a980-e8fa-11e8-9e11-d249286cec88.png)

- With RX amplifiers Always ON: RSSI = **-21dBm** at 433.375MHz
![screenshot_20181115-171632](https://user-images.githubusercontent.com/4953605/48566076-3ac11300-e8fa-11e8-9f32-a8a81429bc65.png)

- With RX amplifiers in Auto mode: RSSI = **-21dBm** at 433.4MHz
![screenshot_20181115-171612](https://user-images.githubusercontent.com/4953605/48566075-3ac11300-e8fa-11e8-83bc-5dcf2c62316b.png)

So I assume that RX power amplifier option does work.

Please re-open in case I am wrong.
Thanks.

**Comment by TadasSu** [comment]
I can not reproduce issue on latest firmware too. It was on older one.
