### ISSUE TITLE
Sync Word does not work on 3bit encoding

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#66]
Sync Word does not work on 3bit encoding. For example I can not get sync word 0000FF to work. URH show random spikes, but not any of 0's or 1's

**Comment by trollwookiee** [comment]
I noticed an issue, maybe not linked to this one: there is an empty space between synchro and codeword corresponding to 1 byte of data. But this is regardless of encoding base (occurs in base 2/3/4). Not sure this is what you are refering to...

I have opened https://github.com/ComThings/PandwaRF/issues/70 to track

**Comment by trollwookiee** [comment]
Issue #70 is fixed, but I need more detail for this issue to know if it is related. A screenshot showing paramters would be great

**Comment by TadasSu** [comment]
I have these when I use HT12E template for 3bit input:
![ss_2](https://user-images.githubusercontent.com/6928835/47938216-086fe880-deec-11e8-9b6f-c1d962e4e89a.png)
![ss_1](https://user-images.githubusercontent.com/6928835/47938217-086fe880-deec-11e8-8dc8-39e20ad2820e.png)
![screenshot_20181102-220705](https://user-images.githubusercontent.com/6928835/47938249-20e00300-deec-11e8-8119-240909a1109a.jpg)

I can not input 3bit on other templates (or without template).
Relates to #71

**Comment by TadasSu** [comment]
update:
If I set sync word in json template, it works. It does not work only if used without custom template.

**Comment by trollwookiee** [comment]
I can't reproduce. No spikes at all on Nordic v0.11.1 and CC1111 v1.1.1. What is your FW versions for Nordic and CC1111 ?

**Comment by TadasSu** [comment]
Nordic: 0.11.1
CC1111: 1.0.24

I can reproduce it every time:
Select model HT12E_A10D2 template.
Change Mask to all F's
Change Value to all 0's
Change SyncWord to 0000FF

**Comment by trollwookiee** [comment]
Please update CC1111 version to 1.1.1.

**Comment by TadasSu** [comment]
> Last CC1111 FW Version: Unknown
 in FW tab.

**Comment by trollwookiee** [comment]
CC1111 FW update issue shall be fixed. Please try updating again.

**Comment by TadasSu** [comment]
FW updated successfully.
I will try to reproduce issue with new fw later.

**Comment by TadasSu** [comment]
I can reproduce issue with new fw too.
(Data Rate: **25 600**)

**Comment by trollwookiee** [comment]
Fixed (a long time ago)
