### ISSUE TITLE
GUI requests: tiny button to clear specan

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#72]
1) it would be nice to have one tiny button anywhere in specan tab to clear it.
No I toggle 'Max ever rssi' to have empty graph without stopping specan.

**Comment by trollwookiee** [comment]
Edited and splitted this request in : 
- https://github.com/ComThings/PandwaRF/issues/72
- https://github.com/ComThings/PandwaRF/issues/73
- https://github.com/ComThings/PandwaRF/issues/74

For the future, please split requests or bugs into single issues

**Comment by trollwookiee** [comment]
Fixed
