### ISSUE TITLE
Transmission does not work with USB connection

### ISSUE THREAD

**Issue by Massimaux** [ComThings/PandwaRF#77]
Hi,

I've had the PandwaRF dongle for about 10 days. The USB connection for both Rx and Tx worked well with the original firmware.

Then, I upgraded the firmware as suggested by the PandwaRF application. After that only the BLE connection works. The USB does not work for transmissions. When I press Xmit, it gets stuck and the RED LED remains ON.

What happened? Is this problem caused by the firmware upgrade or is it something else?

Thank you

**Comment by trollwookiee** [comment]
Can you precise from what version you upgraded from and to ?

**Comment by trollwookiee** [comment]
Update: USB works also with LGE Nexus 5x, Android 8.1.0, API 27

**Comment by trollwookiee** [comment]
In conclusion, I think USB works. I have noticed 2/3 minor issues - icon not updated, splash screen not displayed, reconnection in BLE at the same time as USB, etc... - that I will fix, but nothing really blocking.

**Comment by Massimaux** [comment]
Thank you for the prompt responses.

Attached is the firmware configuration. I tried it with two identical phones (Huawei P10 Lite, Android 8.0.0) and the same problem happens on both phones.
![screenshot_20181119-132134](https://user-images.githubusercontent.com/45128548/48707869-14a0b900-ec01-11e8-9cb8-8e18857d6784.jpg)

Also, please have a look at the cable that I'm using for the USB connection. It's a concatenation of two USB cables so that the two ends are micro USB Type B. But the two ends of this cable (let's call them End1 and End2) do not seem to be equal. I noticed two different situations:
- when End1 is plugged in the PandwaRF, USB is detected and only Rx mode works
- when End2 is plugged in the PandwaRF, USB is not detected and nothing works
![20181119_132510](https://user-images.githubusercontent.com/45128548/48707874-1a969a00-ec01-11e8-8709-e7933e828dfc.jpg)

Perhaps this cable is not suitable for the USB connection. However, it used to work 10 days ago and that's what confuses me. :(

**Comment by Massimaux** [comment]
Thank you for the prompt responses.

Attached is the firmware configuration. I tried it with two identical phones (Huawei P10 Lite, Android 8.0.0) and the same problem happens on both phones.
![screenshot_20181119-134654](https://user-images.githubusercontent.com/45128548/48708062-c344f980-ec01-11e8-96ab-bd9669dddf9b.jpg)

Also, please have a look at the cable that I'm using for the USB connection. It's a concatenation of two USB cables so that the two ends are micro USB Type B. But the two ends of this cable (let's call them End1 and End2) do not seem to be equal. I noticed two different situations:

when End1 is plugged in the PandwaRF, USB is detected and only Rx mode works
when End2 is plugged in the PandwaRF, USB is not detected and nothing works

Perhaps this cable is not suitable for the USB connection. However, it used to work 10 days ago and that's what confuses me. :(

![20181119_132510](https://user-images.githubusercontent.com/45128548/48708088-d952ba00-ec01-11e8-8d85-46782e3fcf9c.jpg)

**Comment by trollwookiee** [comment]
I don't think the cable is correct (don't know why it worked though...)
Please check that the pinout is the same as the following diagram:
![usb otg cable pinout](https://user-images.githubusercontent.com/4953605/48715969-93ecb780-ec16-11e8-8560-0435ff52f4a9.gif)

The **direction is important**:
- A device is the host (the smartphone)
- B device is the PandwaRF

Here is a cable that is guaranteed to work.
https://www.ebay.fr/itm/Micro-USB-male-to-Micro-USB-Male-data-charger-cable-for-MP4-Mobile-Phone/281892636170

**Comment by Massimaux** [comment]
Good to know, thanks!

I already ordered this cable. Is that the right one or I made a mistake?

http://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.0.0.21d64c4dmCN6pX&orderId=96455028899404&productId=32808154910

**Comment by Massimaux** [comment]
Good to know, thanks!

I already ordered this cable. Is that the right one or I made a mistake?

http://www.aliexpress.com/item/1pc-Micro-USB-Type-B-Male-To-Micro-B-Male-5-Pin-Converter-OTG-Adapter-Lead/32808154910.html?spm=a2g0s.12269583.0.0.17b5240dTBHQa7

**Comment by trollwookiee** [comment]
I usually prefer cables with color to indicate which side is what, but it should be OK if product description is correct.

**Comment by Massimaux** [comment]
Do you think this product description is OK?

Micro USB Type B Male To Micro B Male 5Pin Converter OTG Adapter Lead Data Cable

Compatible only with the Android Smartphones and Tablets having the USB Host OTG features





On Monday, November 19, 2018, 4:43:07 PM GMT+1, Djamil Elaidi <notifications@github.com> wrote: 





Closed #77.

**Comment by trollwookiee** [comment]
Yes should be OK.

**Comment by trollwookiee** [comment]
Here is a final summary of USB tests and fixes.
With Firmware Nordic v0.11.1, CC1111 v1.1.1, **USB works fine** with:

- Motorola MotoE2 on Android 6.0, API 23
- LGE Nexus 5x, Android 8.1.0, API 27   
- Samsung Galaxy S5 SM-G900T, Android 6.01.1, API 23
- Xiaomi Redmi 5, Android 7.1.2, API 25

**But some USB improvement/stability fixes will be released in Android App v1.4.21**

**Comment by trollwookiee** [comment]
Updated https://github.com/ComThings/PandwaRF/wiki/Android-USB-Connection
