### ISSUE TITLE
copy/paste the sniffed data

### ISSUE THREAD

**Issue by trollwookiee** [ComThings/PandwaRF#79]
Also, it would be great if it was possible to copy/paste the sniffed data. I don't understand why it is locked (I know I can write or erase, but I would like to SELECT it).

_Originally posted by @ferprat in https://github.com/ComThings/PandwaRF/issues/58#issuecomment-442784183_

**Comment by trollwookiee** [comment]
RX/TX Copy/Paste is coming.
ETA is March 2019

**Comment by thesle3p** [comment]
Any update on this?

**Comment by trollwookiee** [comment]
Feature was ready on a branch, but not merged because copy/paste doesn't work on some phone (Nexus 5X, Motorola E2, ...)
The branch has been merged anyway, so many other phones will benefit from copy/paste.
Will be available in Android app v1.6.9
