### ISSUE TITLE
Bug value in SpecAn tab

### ISSUE THREAD

**Issue by Sens-tech** [ComThings/PandwaRF#8]
**When you are in the "SpecAn" tab, the Start Freq changes regularly for -1.275MHz which then indicates an error.**

**The phone I use :**
 - HTC One (m7)
 - Android 5.0.1

<img src="https://scontent.xx.fbcdn.net/v/t34.0-12/16780374_334206523642215_798494549_n.jpg?oh=066196f79d9b2da45f67f02525567d5e&oe=58A7B919">

**Comment by trollwookiee** [comment]
Fixed in 1.2.36
