### ISSUE TITLE
Data rate compute

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#80]
Data rate 'Compute' always shows 5000.
('Measurement' works correctly)

**Comment by TadasSu** [comment]
False alarm.
If set to 20000, work correctly.

**Comment by trollwookiee** [comment]
Note: the Compute button takes the (data and data rate) as an input to computation. 
The data rate is supposed to be the DR at which the data has been captured.
Therefore if the data rate is changed after capture, the compute DR button returns false results...
