### ISSUE TITLE
Rogue reboots when data rate 20000

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#81]
Rogue reboots if data rate 20000.
https://youtu.be/XCc98IQuxrA

**Comment by TadasSu** [comment]
It seams that device reboots only if captured payload is bigger then desired payload (if I keep pressing button on keyfob)

**Comment by trollwookiee** [comment]
Ok I see. BLE throughput is smaller than 20000 bits/s so PandwaRF fail to evacuate data to app.
This is clearly a known issue (at least internally), and I will try to address it shortly.
Things will get better when I will release RX frame compression for Rogue line.

**Comment by trollwookiee** [comment]
Frame compression and data enqueuing are coming soon for the Rogue.
This will allow to fix crashes at high data rate.

**Comment by trollwookiee** [comment]
New releases has been made yesterday:

- App version 1.6.0
- Nordic FW version 0.11.6
- CC1111 FW version 1.1.9

Please indicate if issue still occurs.
