### ISSUE TITLE
Unknown CC1111 FW flavor in FW tab, need to reboot pandwarf to get it work again

### ISSUE THREAD

**Issue by trollwookiee** [ComThings/PandwaRF#82]
On behalf of TadasSu:
when Rogue migration is available for CC1111 pops up, there is no CC1111 FW flavor in FW tab (shows unknown) and I need to reboot pandwarf to get it work again

**Comment by trollwookiee** [comment]
@TadasSu when you have unknown CC1111 FW flavor, can you go to Bus service and click on CC1111 Hard reset button ? instead of resetting physically the PandwaRF

**Comment by TadasSu** [comment]
CC1111 Hard reset button helps. Then I get "RF power amplifiers mismatch" warning.

**Comment by trollwookiee** [comment]
Ok great. 
RF power amplifiers mismatch" warning is normal then, as CC1111 has been reset and lost previous settings.

**Comment by trollwookiee** [comment]
Please reopen if it reappear
