### ISSUE TITLE
RX on 2FSK not working

### ISSUE THREAD

**Issue by asiudoisjdfo** [ComThings/PandwaRF#89]
Hi,

I cant make it receive 2FSK at all. I've seen the "known issues" page which mentions TX on 2FSK (which is my next step.. ) but whats up with the RX function? Specan works fine, and I believe OOK/ASK is fine as well. But I am seeing "Something has gone wrong" like a milion times. Device is bonded, firmwares updated as per today, so...whats up?

**Comment by trollwookiee** [comment]
Do you have the "Something has gone wrong" issue only for 2FSK ?

**Comment by trollwookiee** [comment]
Fixed in Android 1.5.1
