### ISSUE TITLE
Rogue does not work after transmitting tx

### ISSUE THREAD

**Issue by pwncc** [ComThings/PandwaRF#94]
After transmitting TX rogue will not receive or send again. Led does not come on. Works again when app is restarted

**Comment by trollwookiee** [comment]
Could you please indicate:
- App version
- Nordic FW version
- CC1111 FW version

**Comment by trollwookiee** [comment]
New releases has been made yesterday:
- App version 1.6.0
- Nordic FW version 0.11.6
- CC1111 FW version 1.1.9

Please indicate if issue still occurs.

**Comment by pwncc** [comment]
Issue fixed!

**Comment by trollwookiee** [comment]
ok thanks for feedback
