### ISSUE TITLE
Marauder - Not detected as a Marauder

### ISSUE THREAD

**Issue by sjames02** [ComThings/PandwaRF#96]
I own a 'Marauder Standard' and very frequently when trying to fetch data or configure a capture frequency the device fails to function. When I check the logs it reports "Feature not possible on this device. Requires a Marauder device."

The device has been updated and reports as a Marauder Standard within the information page. The application is also the newest available within the Google Play store.

Your help would be much appreciated.

**Comment by trollwookiee** [comment]
New app release 0.0.5 + Nordic 0.11.10 + CC1111 1.1.13 are pushed today.
Please try again with these versions. Before updating the app, don't forget to save your RF captures.

**Comment by trollwookiee** [comment]
Do you still have issue ?

**Comment by trollwookiee** [comment]
Not able to reproduce the issue any more since app v0.0.5
